### ISSUE TITLE
Crash [goety 1.10.3]

### ISSUE THREAD

**Issue by j4p4n4s4** [Polarice3/Goety#3]
I was testing in creativ...

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 26/05/22 19:22
Description: Ticking entity

java.lang.ClassCastException: com.Polarice3.Goety.common.entities.hostile.illagers.EnviokerEntity cannot be cast to net.minecraft.entity.player.PlayerEntity
	at com.Polarice3.Goety.common.entities.bosses.ApostleEntity$SkeletonSpellGoal.castSpell(ApostleEntity.java:931) ~[goety:1.10.3] {re:classloading}
	at com.Polarice3.Goety.common.entities.hostile.cultists.SpellcastingCultistEntity$UseSpellGoal.func_75246_d(SpellcastingCultistEntity.java:193) ~[goety:1.10.3] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:136) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:977) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,pl:mixin:APP:META-INF/respawnableanimals.mixins.json:MobEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:META-INF/sneakymagic.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bigbrain.mixins.json:LivingEntityMixin,pl:mixin:APP:immersive_armors.mixin.json:MixinLivingEntity,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:relics.mixins.json:MixinLivingEntity,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:companion_bats.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:683) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,pl:mixin:APP:META-INF/respawnableanimals.mixins.json:MobEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:META-INF/sneakymagic.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.monster.AbstractRaiderEntity.func_70636_d(SourceFile:114) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:savageandravage.mixins.json:AbstractRaiderEntityMixin,pl:mixin:APP:savageandravage.mixins.json:IRaiderAccessor,pl:mixin:A}
	at com.Polarice3.Goety.common.entities.bosses.ApostleEntity.func_70636_d(ApostleEntity.java:471) ~[goety:1.10.3] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bigbrain.mixins.json:LivingEntityMixin,pl:mixin:APP:immersive_armors.mixin.json:MixinLivingEntity,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:relics.mixins.json:MixinLivingEntity,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:companion_bats.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,pl:mixin:APP:META-INF/respawnableanimals.mixins.json:MobEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:META-INF/sneakymagic.mixins.json:MobEntityMixin,pl:mixin:A}
	at com.Polarice3.Goety.common.entities.hostile.cultists.SpellcastingCultistEntity.func_70071_h_(SpellcastingCultistEntity.java:70) ~[goety:1.10.3] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spawnermod.mixins.json:UpdateNeighborMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.Polarice3.Goety.common.entities.bosses.ApostleEntity$SkeletonSpellGoal.castSpell(ApostleEntity.java:931) ~[goety:1.10.3] {re:classloading}
	at com.Polarice3.Goety.common.entities.hostile.cultists.SpellcastingCultistEntity$UseSpellGoal.func_75246_d(SpellcastingCultistEntity.java:193) ~[goety:1.10.3] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:136) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:977) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,pl:mixin:APP:META-INF/respawnableanimals.mixins.json:MobEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:META-INF/sneakymagic.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bigbrain.mixins.json:LivingEntityMixin,pl:mixin:APP:immersive_armors.mixin.json:MixinLivingEntity,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:relics.mixins.json:MixinLivingEntity,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:companion_bats.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:683) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,pl:mixin:APP:META-INF/respawnableanimals.mixins.json:MobEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:META-INF/sneakymagic.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.monster.AbstractRaiderEntity.func_70636_d(SourceFile:114) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:savageandravage.mixins.json:AbstractRaiderEntityMixin,pl:mixin:APP:savageandravage.mixins.json:IRaiderAccessor,pl:mixin:A}
	at com.Polarice3.Goety.common.entities.bosses.ApostleEntity.func_70636_d(ApostleEntity.java:471) ~[goety:1.10.3] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bigbrain.mixins.json:LivingEntityMixin,pl:mixin:APP:immersive_armors.mixin.json:MixinLivingEntity,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:relics.mixins.json:MixinLivingEntity,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:companion_bats.mixins.json:LivingEntityMixin,pl:mixin:APP:curioofundying.mixins.json:LivingEntityMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:syp:MobEntity,pl:mixin:APP:META-INF/respawnableanimals.mixins.json:MobEntityMixin,pl:mixin:APP:mostructures.mixins.json:MixinMobEntity,pl:mixin:APP:META-INF/sneakymagic.mixins.json:MobEntityMixin,pl:mixin:A}
	at com.Polarice3.Goety.common.entities.hostile.cultists.SpellcastingCultistEntity.func_70071_h_(SpellcastingCultistEntity.java:70) ~[goety:1.10.3] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: goety:apostle (com.Polarice3.Goety.common.entities.bosses.ApostleEntity)
	Entity ID: 14
	Entity Name: Krosen The Witch King
	Entity's Exact location: 233.67, 64.94, 4.55
	Entity's Block location: World: (233,64,4), Chunk: (at 9,4,4 in 14,0; contains blocks 224,0,0 to 239,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.06, -0.08, 0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spawnermod.mixins.json:UpdateNeighborMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}

**Comment by Polarice3** [comment]
Good catch! Will be fixed in the next update!

**Comment by Polarice3** [comment]
Should be fixed for the current update!
