### ISSUE TITLE
Random Crash during gameplay

### ISSUE THREAD

**Issue by luffykick** [Polarice3/Goety#4]
While playing I randomly get this crash. I think this happens when an arrow hits another entity.
```
Time: 6/26/22 3:21 AM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.entity.projectile.ArrowEntity cannot be cast to net.minecraft.entity.LivingEntity
	at com.Polarice3.Goety.common.events.SoulEnergyEvent.onLivingDeathEvent(SoulEnergyEvent.java:113) ~[goety:1.15.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2654_SoulEnergyEvent_onLivingDeathEvent_LivingDeathEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:360) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:dungeons_plus.mixins.json:ForgeHooksMixin,pl:mixin:APP:fastbenchminusreplacement.mixins.json:ForgeHooksMixin,pl:mixin:APP:bountifulbaubles-forge.mixins.json:MixinForgeHooks,pl:mixin:APP:mixins.tswap.json:ForgeHooksAccessor,pl:mixin:APP:mixins.tswap.json:ForgeHooksMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntity.java:1183) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf::default,xf::default,xf::default,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf::default,xf::default,xf::default,pl:mixin:APP:entitycollisionfpsfix.mixins.json:MixinLivingEntity,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:cgm.mixins.json:common.LivingEntityMixin,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:APP:mixins.biomancy.json:LivingEntityAccessor,pl:mixin:APP:mixins.biomancy.json:LivingEntityMixin,pl:mixin:APP:mining-master.mixins.json:MixinLivingEntity,pl:mixin:APP:secondchanceforge.mixins.json:MixinLivingEntity,pl:mixin:APP:bigbrain.mixins.json:LivingEntityMixin,pl:mixin:APP:bountifulbaubles.mixins.json:MixinLivingEntity,pl:mixin:APP:crockpot.mixins.json:LivingEntityMixin,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:relics.mixins.json:MixinLivingEntity,pl:mixin:APP:resourcefulbees.mixins.json:LivingEntityAccessor,pl:mixin:APP:resourcefulbees.mixins.json:MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:APP:seeker_compass.mixins.json:LivingEntityMixin,pl:mixin:APP:seeker_compass.mixins.json:client.LivingEntityMixin,pl:mixin:APP:allurement.mixins.json:LivingEntityAccessor,pl:mixin:APP:allurement.mixins.json:LivingEntityMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1059) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf::default,xf::default,xf::default,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf::default,xf::default,xf::default,pl:mixin:APP:entitycollisionfpsfix.mixins.json:MixinLivingEntity,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity,pl:mixin:APP:cgm.mixins.json:common.LivingEntityMixin,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:APP:mixins.biomancy.json:LivingEntityAccessor,pl:mixin:APP:mixins.biomancy.json:LivingEntityMixin,pl:mixin:APP:mining-master.mixins.json:MixinLivingEntity,pl:mixin:APP:secondchanceforge.mixins.json:MixinLivingEntity,pl:mixin:APP:bigbrain.mixins.json:LivingEntityMixin,pl:mixin:APP:bountifulbaubles.mixins.json:MixinLivingEntity,pl:mixin:APP:crockpot.mixins.json:LivingEntityMixin,pl:mixin:APP:blue_skies.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:relics.mixins.json:MixinLivingEntity,pl:mixin:APP:resourcefulbees.mixins.json:LivingEntityAccessor,pl:mixin:APP:resourcefulbees.mixins.json:MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:APP:endergetic.mixins.json:LivingEntityMixin,pl:mixin:APP:seeker_compass.mixins.json:LivingEntityMixin,pl:mixin:APP:seeker_compass.mixins.json:client.LivingEntityMixin,pl:mixin:APP:allurement.mixins.json:LivingEntityAccessor,pl:mixin:APP:allurement.mixins.json:LivingEntityMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.LivingEntityMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70097_a(SourceFile:73) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dungeons_mobs.mixins.json:AbstractArrowEntityMixin,pl:mixin:APP:mining-master.mixins.json:MixinAbstractArrowEntity,pl:mixin:APP:allurement.mixins.json:AbstractArrowEntityMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:AccessorAbstractArrowEntity,pl:mixin:A}
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dungeons_mobs.mixins.json:AbstractArrowEntityMixin,pl:mixin:APP:mining-master.mixins.json:MixinAbstractArrowEntity,pl:mixin:APP:allurement.mixins.json:AbstractArrowEntityMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:AccessorAbstractArrowEntity,pl:mixin:A}
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dungeons_mobs.mixins.json:ArrowAccessor,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,xf::default,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,xf::default,pl:mixin:APP:zawa.mixins.json:ServerLevelMixin,pl:mixin:APP:library_of_exile-mixins.json:ServerWorldMixin,pl:mixin:APP:mixins.biomancy.json:ServerWorldAccessor,pl:mixin:APP:mca.mixin.json:MixinServerWorld,pl:mixin:APP:betternether.mixins.json:ServerWorldMixin,pl:mixin:APP:bountifulbaubles.mixins.json:MixinServerWorld,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:mixins.zycraft.json:world.server.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.World.func_217390_a(MixinWorldRedstone.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,pl:mixin:APP:securitycraft.mixins.json:piston.WorldMixin,pl:mixin:APP:multiblocked.mixins.json:WorldMixin,pl:mixin:APP:mixins.integrated_proxy.json:MixinWorldRedstone,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.collections.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.should_tick_cache.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.block_entity_ticking.support_cache.WorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,xf::default,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,xf::default,pl:mixin:APP:zawa.mixins.json:ServerLevelMixin,pl:mixin:APP:library_of_exile-mixins.json:ServerWorldMixin,pl:mixin:APP:mixins.biomancy.json:ServerWorldAccessor,pl:mixin:APP:mca.mixin.json:MixinServerWorld,pl:mixin:APP:betternether.mixins.json:ServerWorldMixin,pl:mixin:APP:bountifulbaubles.mixins.json:MixinServerWorld,pl:mixin:APP:architects_palette.mixins.json:ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:mixins.zycraft.json:world.server.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:ai.nearby_entity_tracking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:roadrunner.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}
```

**Comment by Polarice3** [comment]
Good catch! Will be fixed in the next Update!
